
//Define Clock source
#define MCU_CLOCK_SOURCE      
#define MCU_CLOCK_SOURCE_HIRC // HXT, LXT, HIRC, LIRC
#define MCU_CLOCK_FREQUENCY   42000000  //Hz

//Define MCU Interfaces
#define MCU_INTERFACE_TMR3
#define TMR3_CLOCK_SOURCE_HIRC // HXT, LXT, LIRC, EXT, HIRC
#define TMR3_OPERATING_MODE   TIMER_PERIODIC_MODE // ONESHOT, PERIODIC, TOGGLE, CONTINUOUS
#define TMR3_OPERATING_FREQ   1000000 //Hz
#define TMR3_CAPTURE_MODE     TIMER_CAPTURE_TRIGGER_COUNTING_MODE // FREE_COUNTING, TRIGGER_COUNTING, COUNTER_RESET
#define TMR3_CAPTURE_EDGE     TIMER_CAPTURE_RISING_THEN_FALLING_EDGE // FALLING, RISING, FALLING_THEN_RISING, RISING_THEN_FALLING 
#define PIN_TC3_PA6
